# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\User\Documents\GameLearning\SelfPlayTool\Dota2TimeTips\ui\ui_screen_tips_ctrl.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dota2ScreenTipsCtrlDlg(object):
    def setupUi(self, Dota2ScreenTipsCtrlDlg):
        Dota2ScreenTipsCtrlDlg.setObjectName("Dota2ScreenTipsCtrlDlg")
        Dota2ScreenTipsCtrlDlg.resize(475, 53)
        Dota2ScreenTipsCtrlDlg.setMinimumSize(QtCore.QSize(0, 0))
        Dota2ScreenTipsCtrlDlg.setMaximumSize(QtCore.QSize(500, 200))
        self.btn_updataGameTime = QtWidgets.QPushButton(Dota2ScreenTipsCtrlDlg)
        self.btn_updataGameTime.setGeometry(QtCore.QRect(340, 0, 61, 51))
        self.btn_updataGameTime.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_updataGameTime.setStyleSheet("background-color: rgba(0, 0, 0, 100);\n"
"color: rgb(255, 255, 255);")
        self.btn_updataGameTime.setObjectName("btn_updataGameTime")
        self.btn_close_tips = QtWidgets.QPushButton(Dota2ScreenTipsCtrlDlg)
        self.btn_close_tips.setGeometry(QtCore.QRect(0, 0, 61, 51))
        self.btn_close_tips.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_close_tips.setStyleSheet("background-color: rgba(0, 0, 0, 100);\n"
"color: rgb(255, 255, 255);")
        self.btn_close_tips.setObjectName("btn_close_tips")
        self.btn_roshan_countdown = QtWidgets.QPushButton(Dota2ScreenTipsCtrlDlg)
        self.btn_roshan_countdown.setGeometry(QtCore.QRect(410, 0, 61, 51))
        self.btn_roshan_countdown.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_roshan_countdown.setStyleSheet("background-color: rgba(0, 0, 0, 100);\n"
"color: rgb(255, 255, 255);")
        self.btn_roshan_countdown.setObjectName("btn_roshan_countdown")
        self.btn_clear_countdown = QtWidgets.QPushButton(Dota2ScreenTipsCtrlDlg)
        self.btn_clear_countdown.setGeometry(QtCore.QRect(70, 0, 61, 51))
        self.btn_clear_countdown.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_clear_countdown.setStyleSheet("background-color: rgba(0, 0, 0, 100);\n"
"color: rgb(255, 255, 255);")
        self.btn_clear_countdown.setObjectName("btn_clear_countdown")
        self.btn_pauseGameTime = QtWidgets.QPushButton(Dota2ScreenTipsCtrlDlg)
        self.btn_pauseGameTime.setGeometry(QtCore.QRect(270, 0, 61, 51))
        self.btn_pauseGameTime.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_pauseGameTime.setStyleSheet("background-color: rgba(0, 0, 0, 100);\n"
"color: rgb(255, 255, 255);")
        self.btn_pauseGameTime.setObjectName("btn_pauseGameTime")

        self.retranslateUi(Dota2ScreenTipsCtrlDlg)
        QtCore.QMetaObject.connectSlotsByName(Dota2ScreenTipsCtrlDlg)

    def retranslateUi(self, Dota2ScreenTipsCtrlDlg):
        _translate = QtCore.QCoreApplication.translate
        Dota2ScreenTipsCtrlDlg.setWindowTitle(_translate("Dota2ScreenTipsCtrlDlg", "控制窗口"))
        self.btn_updataGameTime.setText(_translate("Dota2ScreenTipsCtrlDlg", "启动/刷新\n"
"时间"))
        self.btn_close_tips.setText(_translate("Dota2ScreenTipsCtrlDlg", "关闭\n"
"提词器"))
        self.btn_roshan_countdown.setText(_translate("Dota2ScreenTipsCtrlDlg", "肉山\n"
"倒计时"))
        self.btn_clear_countdown.setText(_translate("Dota2ScreenTipsCtrlDlg", "清除\n"
"倒计时"))
        self.btn_pauseGameTime.setText(_translate("Dota2ScreenTipsCtrlDlg", "暂停\n"
"时间"))
